import type { Oil, FattyAcidProfile } from '../types';

export const OILS: Oil[] = [
    { name: "녹차씨 오일 (Green Tea Seed Oil)", sap: 0.135, ins: 108, fattyAcids: { lauric: 0, myristic: 0, palmitic: 23, stearic: 2, ricinoleic: 0, oleic: 55, linoleic: 18, linolenic: 1 } },
    { name: "님 오일 (Neem Oil)", sap: 0.139, ins: 124, fattyAcids: { lauric: 0, myristic: 0, palmitic: 18, stearic: 16, ricinoleic: 0, oleic: 47, linoleic: 15, linolenic: 1 } },
    { name: "달맞이꽃 오일 (Evening Primrose Oil)", sap: 0.136, ins: 30, fattyAcids: { lauric: 0, myristic: 0, palmitic: 6, stearic: 2, ricinoleic: 0, oleic: 10, linoleic: 72, linolenic: 10 } },
    { name: "동백 오일 (Camellia Oil)", sap: 0.136, ins: 108, fattyAcids: { lauric: 0, myristic: 0, palmitic: 8, stearic: 2, ricinoleic: 0, oleic: 82, linoleic: 7, linolenic: 1 } },
    { name: "마카다미아넛 오일 (Macadamia Nut Oil)", sap: 0.139, ins: 119, fattyAcids: { lauric: 0, myristic: 0, palmitic: 9, stearic: 5, ricinoleic: 0, oleic: 84, linoleic: 2, linolenic: 0 } },
    { name: "마유 (Horse Fat)", sap: 0.140, ins: 140, fattyAcids: { lauric: 0, myristic: 3, palmitic: 26, stearic: 5, ricinoleic: 0, oleic: 38, linoleic: 10, linolenic: 15 } },
    { name: "망고버터 (Mango Butter)", sap: 0.137, ins: 149, fattyAcids: { lauric: 0, myristic: 0, palmitic: 6, stearic: 42, ricinoleic: 0, oleic: 46, linoleic: 3, linolenic: 1 } },
    { name: "모링가 오일 (Moringa Oil)", sap: 0.137, ins: 110, fattyAcids: { lauric: 0, myristic: 0, palmitic: 6, stearic: 6, ricinoleic: 0, oleic: 74, linoleic: 1, linolenic: 0 } },
    { name: "미강유 (Rice Bran Oil)", sap: 0.128, ins: 70, fattyAcids: { lauric: 0, myristic: 0, palmitic: 15, stearic: 1, ricinoleic: 0, oleic: 43, linoleic: 39, linolenic: 1 } },
    { name: "밀랍 (Beeswax)", sap: 0.069, ins: 84, fattyAcids: { lauric: 0, myristic: 0, palmitic: 80, stearic: 20, ricinoleic: 0, oleic: 0, linoleic: 0, linolenic: 0 } },
    { name: "밍크 오일 (Mink Oil)", sap: 0.140, ins: 130, fattyAcids: { lauric: 0, myristic: 2, palmitic: 25, stearic: 8, ricinoleic: 0, oleic: 50, linoleic: 10, linolenic: 1 } },
    { name: "바바수 오일 (Babassu Oil)", sap: 0.175, ins: 230, fattyAcids: { lauric: 44, myristic: 17, palmitic: 9, stearic: 4, ricinoleic: 0, oleic: 16, linoleic: 3, linolenic: 0 } },
    { name: "바오밥 오일 (Baobab Oil)", sap: 0.136, ins: 97, fattyAcids: { lauric: 0, myristic: 0, palmitic: 24, stearic: 4, ricinoleic: 0, oleic: 35, linoleic: 32, linolenic: 1 } },
    { name: "블랙쎄서미 오일 (Sesame Oil)", sap: 0.133, ins: 81, fattyAcids: { lauric: 0, myristic: 0, palmitic: 9, stearic: 4, ricinoleic: 0, oleic: 41, linoleic: 44, linolenic: 1 } },
    { name: "살구씨 오일 (Apricot Kernel Oil)", sap: 0.137, ins: 91, fattyAcids: { lauric: 0, myristic: 0, palmitic: 5, stearic: 2, ricinoleic: 0, oleic: 66, linoleic: 26, linolenic: 1 } },
    { name: "스위트 아몬드 오일 (Sweet Almond Oil)", sap: 0.137, ins: 97, fattyAcids: { lauric: 0, myristic: 0, palmitic: 7, stearic: 2, ricinoleic: 0, oleic: 68, linoleic: 22, linolenic: 0 } },
    { name: "시어버터 (Shea Butter)", sap: 0.128, ins: 116, fattyAcids: { lauric: 0, myristic: 0, palmitic: 8, stearic: 37, ricinoleic: 0, oleic: 48, linoleic: 6, linolenic: 1 } },
    { name: "씨벅턴 오일 (Sea Buckthorn Oil)", sap: 0.137, ins: 78, fattyAcids: { lauric: 0, myristic: 0, palmitic: 32, stearic: 2, ricinoleic: 0, oleic: 50, linoleic: 7, linolenic: 2 } },
    { name: "아르간 오일 (Argan Oil)", sap: 0.136, ins: 100, fattyAcids: { lauric: 0, myristic: 0, palmitic: 13, stearic: 5, ricinoleic: 0, oleic: 47, linoleic: 34, linolenic: 1 } },
    { name: "아보카도 오일 (Avocado Oil)", sap: 0.133, ins: 99, fattyAcids: { lauric: 0, myristic: 0, palmitic: 17, stearic: 2, ricinoleic: 0, oleic: 65, linoleic: 15, linolenic: 1 } },
    { name: "아마씨 오일 (Flaxseed Oil)", sap: 0.135, ins: -6, fattyAcids: { lauric: 0, myristic: 0, palmitic: 6, stearic: 3, ricinoleic: 0, oleic: 19, linoleic: 24, linolenic: 48 } },
    { name: "에뮤 오일 (Emu Oil)", sap: 0.138, ins: 112, fattyAcids: { lauric: 0, myristic: 0, palmitic: 22, stearic: 10, ricinoleic: 0, oleic: 48, linoleic: 15, linolenic: 2 } },
    { name: "옥수수 오일 (Corn Oil)", sap: 0.136, ins: 69, fattyAcids: { lauric: 0, myristic: 0, palmitic: 11, stearic: 2, ricinoleic: 0, oleic: 28, linoleic: 58, linolenic: 1 } },
    { name: "올리브 오일 (Olive Oil)", sap: 0.135, ins: 105, fattyAcids: { lauric: 0, myristic: 0, palmitic: 14, stearic: 3, ricinoleic: 0, oleic: 69, linoleic: 12, linolenic: 1 } },
    { name: "월계수 오일 (Laurel Berry Oil)", sap: 0.141, ins: 130, fattyAcids: { lauric: 30, myristic: 0, palmitic: 15, stearic: 1, ricinoleic: 0, oleic: 30, linoleic: 20, linolenic: 2 } },
    { name: "월넛 오일 (Walnut Oil)", sap: 0.135, ins: 40, fattyAcids: { lauric: 0, myristic: 0, palmitic: 7, stearic: 2, ricinoleic: 0, oleic: 18, linoleic: 60, linolenic: 13 } },
    { name: "윗점 오일 (Wheat Germ Oil)", sap: 0.131, ins: 58, fattyAcids: { lauric: 0, myristic: 0, palmitic: 16, stearic: 2, ricinoleic: 0, oleic: 15, linoleic: 55, linolenic: 7 } },
    { name: "카카오버터 (Cocoa Butter)", sap: 0.138, ins: 157, fattyAcids: { lauric: 0, myristic: 0, palmitic: 28, stearic: 33, ricinoleic: 0, oleic: 35, linoleic: 3, linolenic: 1 } },
    { name: "캐놀라 오일 (Canola Oil)", sap: 0.132, ins: 56, fattyAcids: { lauric: 0, myristic: 0, palmitic: 4, stearic: 2, ricinoleic: 0, oleic: 62, linoleic: 22, linolenic: 10 } },
    { name: "코코넛 오일 (Coconut Oil)", sap: 0.183, ins: 258, fattyAcids: { lauric: 48, myristic: 18, palmitic: 9, stearic: 3, ricinoleic: 0, oleic: 8, linoleic: 2, linolenic: 0 } },
    { name: "콩기름 (Soybean Oil)", sap: 0.135, ins: 61, fattyAcids: { lauric: 0, myristic: 0, palmitic: 11, stearic: 4, ricinoleic: 0, oleic: 24, linoleic: 54, linolenic: 7 } },
    { name: "쿠쿠이넛 오일 (Kukui Nut Oil)", sap: 0.135, ins: 40, fattyAcids: { lauric: 0, myristic: 0, palmitic: 6, stearic: 2, ricinoleic: 0, oleic: 25, linoleic: 40, linolenic: 25 } },
    { name: "팜 오일 (Palm Oil)", sap: 0.142, ins: 145, fattyAcids: { lauric: 0, myristic: 1, palmitic: 44, stearic: 5, ricinoleic: 0, oleic: 39, linoleic: 10, linolenic: 0 } },
    { name: "팜핵유 (Palm Kernel Oil)", sap: 0.156, ins: 227, fattyAcids: { lauric: 48, myristic: 16, palmitic: 8, stearic: 3, ricinoleic: 0, oleic: 15, linoleic: 2, linolenic: 0 } },
    { name: "포도씨 오일 (Grapeseed Oil)", sap: 0.131, ins: 66, fattyAcids: { lauric: 0, myristic: 0, palmitic: 8, stearic: 4, ricinoleic: 0, oleic: 19, linoleic: 68, linolenic: 1 } },
    { name: "피마자 오일 (Castor Oil)", sap: 0.128, ins: 95, fattyAcids: { lauric: 1, myristic: 1, palmitic: 1, stearic: 1, ricinoleic: 89, oleic: 4, linoleic: 3, linolenic: 0 } },
    { name: "햄프씨드 오일 (Hemp Seed Oil)", sap: 0.138, ins: 39, fattyAcids: { lauric: 0, myristic: 0, palmitic: 6, stearic: 2, ricinoleic: 0, oleic: 12, linoleic: 57, linolenic: 20 } },
    { name: "헤이즐넛 오일 (Hazelnut Oil)", sap: 0.136, ins: 94, fattyAcids: { lauric: 0, myristic: 0, palmitic: 5, stearic: 2, ricinoleic: 0, oleic: 78, linoleic: 12, linolenic: 1 } },
    { name: "해바라기 오일 (Sunflower Oil)", sap: 0.136, ins: 63, fattyAcids: { lauric: 0, myristic: 0, palmitic: 6, stearic: 5, ricinoleic: 0, oleic: 20, linoleic: 68, linolenic: 1 } },
    { name: "호호바 오일 (Jojoba Oil)", sap: 0.066, ins: 11, fattyAcids: { lauric: 0, myristic: 0, palmitic: 1, stearic: 0, ricinoleic: 0, oleic: 80, linoleic: 0, linolenic: 0 } },
    { name: "홍화씨 오일 (Safflower Oil)", sap: 0.136, ins: 55, fattyAcids: { lauric: 0, myristic: 0, palmitic: 7, stearic: 3, ricinoleic: 0, oleic: 15, linoleic: 75, linolenic: 0 } },
];

export const FATTY_ACID_NAMES: { [key in keyof FattyAcidProfile]: string } = {
    lauric: "라우르산 (Lauric)",
    myristic: "미리스트산 (Myristic)",
    palmitic: "팔미트산 (Palmitic)",
    stearic: "스테아르산 (Stearic)",
    ricinoleic: "리시놀레산 (Ricinoleic)",
    oleic: "올레산 (Oleic)",
    linoleic: "리놀레산 (Linoleic)",
    linolenic: "리놀렌산 (Linolenic)"
};

export const PROPERTY_RANGES: { [key: string]: { min: number, max: number, name: string } } = {
    hardness: { min: 29, max: 54, name: '경도 (Hardness)' },
    cleansing: { min: 12, max: 22, name: '세정력 (Cleansing)' },
    conditioning: { min: 44, max: 69, name: '보습력 (Conditioning)' },
    bubbly: { min: 14, max: 46, name: '거품 (Bubbly)' },
    creamy: { min: 16, max: 48, name: '크리미 (Creamy)' },
    ins: { min: 136, max: 165, name: 'INS' },
};
